# MobScores default configuration
ScoreTable:
  DROWNED: 25
  ENDERMAN: 100
  GUARDIAN: 250
  SILVERFISH: 0
  ELDER_GUARDIAN: 250
  HUSK: 25
  BLAZE: 100
  GHAST: 250
  ENDERMITE: 1000
  SPIDER: 50
  PILLAGER: 25
  GIANT: 250
  END_CRYSTAL: 250
  SKELETON: 50
  WITHER_SKELETON: 100
  CREEPER: 50
  ZOMBIE: 25
  CAVE_SPIDER: 100
  SLIME: 100
  RAVAGER: 50
  SHULKER: 50