name: Gradle Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: headhunter45/ScoreKeeper
          path: ScoreKeeper
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew publishToMavenLocal
        working-directory: ScoreKeeper
      - run: ./gradlew test build